### ISSUE TITLE
Add support for 2020.2 EAP series

### ISSUE THREAD

**Issue by astrolemonade** [elliotwaite/jetbrains-godot-theme#1]

**Comment by elliotwaite** [comment]
I just uploaded a new version (v1.0.8) which I think should fix this issue. It's still being reviewed but should be available within 24 hours. Let me know if it doesn't resolve the issue.

**Comment by panckreous** [comment]
Any chance to get updated for the 2021.2 EAPs? Thanks

**Comment by elliotwaite** [comment]
@panckreous, thanks for letting me know that it isn't currently working with the latest EAP. I just submitted an update that will fix this issue, version 1.0.11 (it's currently pending review). I also fixed the plugin so that it should now be compatible with all future EAP versions.

**Comment by elliotwaite** [comment]
The new version (1.0.11) has been approved should now be installable on all current and future EAP versions. I am going to close this issue, but if for some reason this latest update doesn't solve this issue, please reopen this issue.
