### ISSUE TITLE
color of mnemonic bookmark 

### ISSUE THREAD

**Issue by optionals** [elliotwaite/jetbrains-godot-theme#2]
now:
<img width="619" alt="截屏2021-08-10 下午3 12 13" src="https://user-images.githubusercontent.com/7846036/128826753-3030bc07-a01b-4bd6-8393-fcb1a24d7acc.png">
expected:
<img width="635" alt="截屏2021-08-10 下午3 12 45" src="https://user-images.githubusercontent.com/7846036/128826771-1a012642-6922-4b27-b75d-c45792d964bc.png">

**Comment by elliotwaite** [comment]
Thank you for reporting this, this is very helpful. I tried to solve this issue but was unable to figure out the specific theme attribute keys that would adjust these colors. I've actually had this issue before of not being able to figure out the attribute keys when I tried to set the welcome-screen project-selection-panel background color. I just opened a new issue about this on the Jetbrains website, so hopefully someone over there will be able to help:
https://youtrack.jetbrains.com/issue/DOC-12781

**Comment by optionals** [comment]
> Thank you for reporting this, this is very helpful. I tried to solve this issue but was unable to figure out the specific theme attribute keys that would adjust these colors. I've actually had this issue before of not being able to figure out the attribute keys when I tried to set the welcome-screen project-selection-panel background color. I just opened a new issue about this on the Jetbrains website, so hopefully someone over there will be able to help:
> https://youtrack.jetbrains.com/issue/DOC-12781
I found this. Does it help?
https://github.com/JetBrains/intellij-community/blob/master/platform/platform-resources/src/themes/metadata/IntelliJPlatform.themeMetadata.json

**Comment by optionals** [comment]
It is mentioned on IntelliJ [Platform UI Guidelines ](https://jetbrains.design/intellij/principles/platform_theme_colors/#ui-components.)

**Comment by elliotwaite** [comment]
Yes, that helped!

I realized I was referencing an outdated version of the theme metadata file:
https://github.com/elliotwaite/jetbrains-cyberpunk-theme/blob/master/scripts/debug/theme_metadata/IntelliJPlatform.themeMetadata.json

The latest version has the keys I was looking for:
https://github.com/JetBrains/intellij-community/blob/master/platform/platform-resources/src/themes/metadata/IntelliJPlatform.themeMetadata.json

I'll update the theme and release the new version today. It should make it through the review process within the next few days. I'll post a follow-up comment here when it should be available for download.

**Comment by optionals** [comment]
I am glad it helped，and looking forward to the fixed version

**Comment by elliotwaite** [comment]
The updated version, 1.0.12, should now be available for download. When you get the chance, can you test it out to make sure it resolves this issue for you, and feel free to let me know if you would prefer the colors to be different than what I chose.

**Comment by optionals** [comment]
The problem was solved after the update and the color is now good. Thanks for your timely reply and update

**Comment by elliotwaite** [comment]
Glad to hear it. And thanks again for reporting this issue.
