### ISSUE TITLE
Metadata color is not set

### ISSUE THREAD

**Issue by bfedie518** [elliotwaite/jetbrains-godot-theme#3]
The theme does not currently set the color for metadata (marked with @).  The default color in Godot is #FFB373

'Metadata' color can be set under 'Language Defaults', and annotations/decorators in other languages can be set to inherit from Metadata.

P.S. Thanks for making this theme.  It's my go-to theme for IntelliJ and Android Studio.

**Comment by elliotwaite** [comment]
Thanks for the suggestion. I don't have time to change this now, but I may have time in a week or so to update this.

**Comment by elliotwaite** [comment]
Actually, I decided to just update it real quick. The new version (1.1.0) has been submitted for review and should be available soon. Thanks again for the suggestion.
