### ISSUE TITLE
Add more color schemes

### ISSUE THREAD

**Issue by palp1tate** [elliotwaite/jetbrains-godot-theme#6]
![image](https://github.com/elliotwaite/jetbrains-godot-theme/assets/120303802/eee87b26-222e-43f9-ac13-04fd9721c79c)
As you can see,maybe there is too much white.Other aspects of this theme are excellent, I think it is better than the theme of One Dark.
If you can enhance the color scheme, I will be extremely grateful.

**Comment by elliotwaite** [comment]
Thanks for opening this issue. And I agree that that is a lot of white text.

My main goal for this theme was to mimic the style of the Godot IDE, so if the Godot IDE would color any of that text differently, I'd be open to changing the theme to match the style of the Godot IDE.

However, I don't plan to enhance this theme further than that. If anyone wants to enhance this theme in a way that diverges from the style of the Godot IDE, then the best way to do that might be to fork this repo and create an alternative theme, maybe "Godot Theme Plus" or something. I fully support anyone who wants to fork this repo and improve upon it.

Also, I currently don't have much time to work on this theme, but I'd be open to reviewing PRs. I hope this is understandable.

**Comment by palp1tate** [comment]
> Thanks for opening this issue. And I agree that that is a lot of white text.
> 
> My main goal for this theme was to mimic the style of the Godot IDE, so if the Godot IDE would color any of that text differently, I'd be open to changing the theme to match the style of the Godot IDE.
> 
> However, I don't plan to enhance this theme further than that. If anyone wants to enhance this theme in a way that diverges from the style of the Godot IDE, then the best way to do that might be to fork this repo and create an alternative theme, maybe "Godot Them Plus" or something. I fully support anyone who wants to fork this repo and improve upon it.
> 
> Also, I currently don't have much time to work on this theme, but I'd be open to reviewing PRs. I hope this is understandable.

Get it,thanks.
