### ISSUE TITLE
White Editor for IntelliJ

### ISSUE THREAD

**Issue by smoosa-risk** [elliotwaite/jetbrains-godot-theme#7]
The editor is completely white whenever I use it for IntelliJ 2023.3 with the new UI. Tried restarting the app and the computer many times but the issue has been recurring for a couple months.

![image](https://github.com/elliotwaite/jetbrains-godot-theme/assets/150801004/22d0621c-221a-4fa8-a221-f80a11aa9007)

**Comment by elliotwaite** [comment]
Sounds similar to this issue: https://github.com/elliotwaite/jetbrains-godot-theme/issues/5. Can you see if the info in that issue is helpful?

**Comment by smoosa-risk** [comment]
Very helpful, working now. Thank you very much for the help and for creating this amazing theme!

**Comment by elliotwaite** [comment]
Glad to hear you were able to resolve the issue.
